apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube
  name: sonarqube
  namespace: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:7.1
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          volumeMounts:
            - name: sonar-data
              mountPath: "/opt/sonarqube/data/"
            - name: sonar-extensions
              mountPath: "/opt/sonarqube/extensions/"
          env:
            - name: "SONARQUBE_JDBC_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: "SONARQUBE_JDBC_URL"
              valueFrom:
                configMapKeyRef:
                  name: sonar-config
                  key: url
            - name: "SONARQUBE_JDBC_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
          ports:
            - containerPort: 9000
              protocol: TCP
      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: sonar-data
        - name: sonar-extensions
          persistentVolumeClaim:
            claimName: sonar-extensions
