dhvlftmd52@cloudshell:~/k8s-prometheus-grafana/prometheus/my-prometheus-grafana (tidy-weaver-417707)$ cat kube-state-svc.yaml 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
  - name: telemetry
    port: 8081
    targetPort: telemetry
  selector:
    app: kube-state-metrics
