apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 211.183.3.201-211.183.3.211 # 해당 네트워크 대역으로 LB 생성
      - 211.183.3.231-211.183.3.239 # 해당 네트워크 대역으로 LB 생성
